---
name: Build and Test Steckschwein-Emulator

on:
  push:
    branches:
      - master

permissions:                    # Füge diese Zeile hinzu
  contents: write                # Stellt sicher, dass die Action Schreibberechtigungen für Inhalte hat

jobs:

  build:

    runs-on: ubuntu-24.04

    steps:
    - name: checkout
      uses: actions/checkout@v4

    - name: install stuff
      run: sudo apt install build-essential:native debhelper libsdl2-dev libinih-dev --no-install-recommends

    - name: build
      run: make -j 8

    - name: make deb
      run: make deb
