name: Build and Test Steckschwein-Emulator

on:
  push:
    branches: [ "master", "featuew/*", "bugfix/*" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-24.04

    steps:
    - name: checkout
      uses: actions/checkout@v4
      
    - name: install libs
      run: apt install libsdl2-dev libinih-dev
