---
name: Build and Test Steckschwein-Emulator

on:
  push:
    branches:
      - master

permissions:                    # Füge diese Zeile hinzu
  contents: write                # Stellt sicher, dass die Action Schreibberechtigungen für Inhalte hat

jobs:

  build:

    runs-on: ubuntu-24.04

    steps:
    - name: checkout
      uses: actions/checkout@v4

    - name: install libs
      run: apt install libsdl2-dev libinih-dev
